apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkobjects-pod
spec:
  replicas: 250
  selector:
    matchLabels:
      app: mkobjects
  template:
    metadata:
      labels:
        app: mkobjects
    spec:
      containers:
      - name: mkobjects-container
        image: thartland/stressos:lancs
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "120m"
        env:
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mwt2creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mwt2creds
                key: AWS_SECRET_ACCESS_KEY
          - name: BUCKET_NAME
            value: "tgh_stressos"
          - name: ENDPOINT_HOSTNAME
            value: "ceph-s3.mwt2.org"
          - name: ENDPOINT_PORT
            value: "80"
          - name: OBJ_MEAN_KB
            value: "2000"
          - name: OBJ_STDDEV_KB
            value: "0"
          - name: NUM_THREADS
            value: "4"
          - name: IS_SECURE
            value: "0"
